# Generated by Django 3.2.10 on 2022-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="nb_employee",
            field=models.IntegerField(default=0),
        ),
    ]
