# Generated by Django 3.2.10 on 2022-12-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("account", "0003_alter_account_nb_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.address",
            ),
        ),
    ]
