# Generated by Django 3.2.10 on 2023-03-10 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_auto_20230119_2255"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
