# Generated by Django 3.2.10 on 2023-04-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_account_create_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBanned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
            ],
        ),
    ]
