# Generated by Django 3.2.10 on 2023-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_ipbanned"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
