# Generated by Django 3.2.10 on 2023-04-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_account_is_banned"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IPBanned",
        ),
    ]
