# Generated by Django 3.2.10 on 2022-11-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposition",
            name="status",
            field=models.CharField(
                choices=[("accepted", "Accepted"), ("declined", "Declined")],
                max_length=255,
                null=True,
            ),
        ),
    ]
