# Generated by Django 3.2.10 on 2022-12-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_locationproduct_locationproposition"),
        ("product", "0004_auto_20221216_2344"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.locationproduct",
            ),
        ),
    ]
