# Generated by Django 3.2.10 on 2022-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("additional_information", models.CharField(max_length=255)),
            ],
        ),
    ]
