# Generated by Django 3.2.10 on 2022-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="additional_information",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
