# Generated by Django 3.2.10 on 2022-12-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_alter_address_additional_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationProposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
